import type { CharacterGrid } from '@/shared/types/index.ts';

interface PlaintextOptions {
  includeMetadata?: boolean;
  sourceFilename?: string;
  sourceWidth?: number;
  sourceHeight?: number;
  cols: number;
  rows: number;
  charsetName?: string;
  modeName?: string;
}

export function formatPlaintext(
  grid: CharacterGrid,
  options: PlaintextOptions,
): string {
  const lines: string[] = [];

  if (options.includeMetadata) {
    lines.push('# Generated by Glyph');
    if (options.sourceFilename) {
      const dims =
        options.sourceWidth && options.sourceHeight
          ? ` (${options.sourceWidth}x${options.sourceHeight})`
          : '';
      lines.push(`# Source: ${options.sourceFilename}${dims}`);
    }
    const parts = [`${options.cols}x${options.rows}`];
    if (options.charsetName) parts.push(`Charset: ${options.charsetName}`);
    if (options.modeName) parts.push(`Mode: ${options.modeName}`);
    lines.push(`# Resolution: ${parts.join(' | ')}`);
    lines.push('');
  }

  for (const row of grid) {
    lines.push(row.map((cell) => cell.char).join(''));
  }

  return lines.join('\n');
}

/**
 * Wraps plaintext output in a Markdown fenced code block.
 */
export function formatMarkdownCodeBlock(
  grid: CharacterGrid,
  options: PlaintextOptions,
): string {
  const plaintext = formatPlaintext(grid, options);
  return '```\n' + plaintext + '\n```';
}
